/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Login;

import Main.DBConnection;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author rakibulnasib
 */
public class Register extends PanelCustom {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        button1 = new Swing.Button();
        button2 = new Swing.Button();
        button3 = new Swing.Button();
        button4 = new Swing.Button();
        button5 = new Swing.Button();
        button6 = new Swing.Button();
        button7 = new Swing.Button();
        jLabel2 = new javax.swing.JLabel();
        tfName = new Swing.TextField();
        tfP = new Swing.Password();
        button8 = new Swing.Button();
        tfUN = new Swing.TextField();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tamil MN", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SIGN UP");

        tfName.setForeground(new java.awt.Color(242, 242, 242));
        tfName.setFont(new java.awt.Font("Tamil MN", 0, 14)); // NOI18N
        tfName.setHint("NAME");
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        tfP.setForeground(new java.awt.Color(242, 242, 242));
        tfP.setFont(new java.awt.Font("Tamil MN", 0, 14)); // NOI18N
        tfP.setHint("PASSWORD");

        button8.setBackground(new java.awt.Color(56, 127, 218));
        button8.setForeground(new java.awt.Color(255, 255, 255));
        button8.setText("Sign Up");
        button8.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        tfUN.setForeground(new java.awt.Color(242, 242, 242));
        tfUN.setFont(new java.awt.Font("Tamil MN", 0, 14)); // NOI18N
        tfUN.setHint("USER NAME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button8, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(tfP, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(tfUN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tfUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(tfP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        
        String name = tfName.getText();
        String username = tfUN.getText();
        String password = String.valueOf(tfP.getPassword());
        
        
        if(getAlpha()==0){
            
            if(name.isEmpty() || username.isEmpty() || password.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Fill up the form properly", "Error",JOptionPane.ERROR_MESSAGE);
        }else{
            //Start the Register process
            userRegister(name, username, password);
        }
        }
    }//GEN-LAST:event_button8ActionPerformed
    
    private void userRegister(String name, String username, String password) {
        Connection dbconn = DBConnection.connectDB();
        if(dbconn != null){
        try {
            String sql = "INSERT INTO users (name, username, password) VALUES (?, ?, ?)";
            PreparedStatement st = (PreparedStatement) dbconn.prepareStatement(sql);
            
            st.setString(1, name);
            st.setString(2, username);
            st.setString(3, password);
            
            st.executeUpdate();
            JOptionPane.showMessageDialog(this, "Registration completed", "Register",JOptionPane.INFORMATION_MESSAGE);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Username Error", "Register",JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{
            System.out.println("The Connection is not available");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.Button button1;
    private Swing.Button button2;
    private Swing.Button button3;
    private Swing.Button button4;
    private Swing.Button button5;
    private Swing.Button button6;
    private Swing.Button button7;
    private Swing.Button button8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private Swing.TextField tfName;
    private Swing.Password tfP;
    private Swing.TextField tfUN;
    // End of variables declaration//GEN-END:variables

   
}
