/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import brickbreaker.*;

/**
 *
 * @author rakibulnasib
 */
public class DifficultyMenu extends javax.swing.JFrame {

    /**
     * Creates new form DifficultyMenu
     */
    public DifficultyMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DifficultyPanel = new javax.swing.JPanel();
        panelCustom1 = new Login.PanelCustom();
        buttonBack = new Swing.Button();
        buttonE = new Swing.Button();
        buttonM = new Swing.Button();
        jLabel1 = new javax.swing.JLabel();
        buttonH = new Swing.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DifficultyPanel.setBackground(new java.awt.Color(102, 102, 0));

        panelCustom1.setBackground(new java.awt.Color(204, 204, 0));

        buttonBack.setBackground(new java.awt.Color(102, 102, 0));
        buttonBack.setForeground(new java.awt.Color(204, 204, 0));
        buttonBack.setText("BACK");
        buttonBack.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        panelCustom1.add(buttonBack);
        buttonBack.setBounds(30, 380, 290, 50);

        buttonE.setBackground(new java.awt.Color(102, 102, 0));
        buttonE.setForeground(new java.awt.Color(204, 204, 0));
        buttonE.setText("EASY");
        buttonE.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        buttonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEActionPerformed(evt);
            }
        });
        panelCustom1.add(buttonE);
        buttonE.setBounds(30, 137, 290, 50);

        buttonM.setBackground(new java.awt.Color(102, 102, 0));
        buttonM.setForeground(new java.awt.Color(204, 204, 0));
        buttonM.setText("MEDIUM");
        buttonM.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        buttonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMActionPerformed(evt);
            }
        });
        panelCustom1.add(buttonM);
        buttonM.setBounds(30, 220, 290, 50);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setText("SELECT DIFFICULTY");
        panelCustom1.add(jLabel1);
        jLabel1.setBounds(90, 70, 190, 30);

        buttonH.setBackground(new java.awt.Color(102, 102, 0));
        buttonH.setForeground(new java.awt.Color(204, 204, 0));
        buttonH.setText("HARD");
        buttonH.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        buttonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHActionPerformed(evt);
            }
        });
        panelCustom1.add(buttonH);
        buttonH.setBounds(30, 300, 290, 50);

        javax.swing.GroupLayout DifficultyPanelLayout = new javax.swing.GroupLayout(DifficultyPanel);
        DifficultyPanel.setLayout(DifficultyPanelLayout);
        DifficultyPanelLayout.setHorizontalGroup(
            DifficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DifficultyPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(panelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        DifficultyPanelLayout.setVerticalGroup(
            DifficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DifficultyPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(panelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DifficultyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DifficultyPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        dispose();
        MainMenu M=new MainMenu();
        M.setVisible(true);
       
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEActionPerformed
        // TODO add your handling code here:
        dispose();
        BrickBreaker gm=new BrickBreaker(1);
    }//GEN-LAST:event_buttonEActionPerformed

    private void buttonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMActionPerformed
        // TODO add your handling code here:
         dispose();
        BrickBreaker gm=new BrickBreaker(2);
    }//GEN-LAST:event_buttonMActionPerformed

    private void buttonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHActionPerformed
        // TODO add your handling code here:
        dispose();
        BrickBreaker gm=new BrickBreaker(3);
    }//GEN-LAST:event_buttonHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DifficultyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DifficultyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DifficultyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DifficultyMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DifficultyMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DifficultyPanel;
    private Swing.Button buttonBack;
    private Swing.Button buttonE;
    private Swing.Button buttonH;
    private Swing.Button buttonM;
    private javax.swing.JLabel jLabel1;
    private Login.PanelCustom panelCustom1;
    // End of variables declaration//GEN-END:variables
}
