/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;
//import javax.swing.ImageIcon;

/**
 *
 * @author rakibulnasib
 */
public class MainMenu extends javax.swing.JFrame {

    //ImageIcon img=new ImageIcon("brick-breaker-2.png");
    public MainMenu() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panelCustom1 = new Login.PanelCustom();
        buttonS = new Swing.Button();
        buttonL = new Swing.Button();
        buttonBack = new Swing.Button();
        labelPic = new javax.swing.JLabel();
        buttonH = new Swing.Button();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        panelCustom1.setBackground(new java.awt.Color(0, 204, 204));

        buttonS.setBackground(new java.awt.Color(0, 102, 102));
        buttonS.setForeground(new java.awt.Color(0, 255, 255));
        buttonS.setText("START");
        buttonS.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        buttonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSActionPerformed(evt);
            }
        });
        panelCustom1.add(buttonS);
        buttonS.setBounds(170, 260, 310, 60);

        buttonL.setBackground(new java.awt.Color(0, 102, 102));
        buttonL.setForeground(new java.awt.Color(0, 255, 255));
        buttonL.setText("LEADERBOARD");
        buttonL.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        buttonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLActionPerformed(evt);
            }
        });
        panelCustom1.add(buttonL);
        buttonL.setBounds(170, 340, 310, 60);

        buttonBack.setBackground(new java.awt.Color(0, 102, 102));
        buttonBack.setForeground(new java.awt.Color(51, 255, 255));
        buttonBack.setText("BACK");
        buttonBack.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        panelCustom1.add(buttonBack);
        buttonBack.setBounds(20, 10, 100, 40);

        labelPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/brick-breaker-2.png"))); // NOI18N
        panelCustom1.add(labelPic);
        labelPic.setBounds(190, 10, 280, 240);

        buttonH.setBackground(new java.awt.Color(0, 102, 102));
        buttonH.setForeground(new java.awt.Color(51, 255, 255));
        buttonH.setText("HELP");
        buttonH.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        buttonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHActionPerformed(evt);
            }
        });
        panelCustom1.add(buttonH);
        buttonH.setBounds(170, 420, 310, 60);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(panelCustom1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSActionPerformed
        // TODO add your handling code here:
        dispose();
        DifficultyMenu dm = new DifficultyMenu();
        dm.setVisible(true);
    }//GEN-LAST:event_buttonSActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        dispose();
        Main lb = new Main();
        lb.setVisible(true);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLActionPerformed
        // TODO add your handling code here:
        dispose();
        LeaderBoard lb = new LeaderBoard();
        lb.setVisible(true);
    }//GEN-LAST:event_buttonLActionPerformed

    private void buttonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHActionPerformed
        // TODO add your handling code here:
        dispose();
        helpPage hp=new helpPage();
        hp.setVisible(true);
    }//GEN-LAST:event_buttonHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.Button buttonBack;
    private Swing.Button buttonH;
    private Swing.Button buttonL;
    private Swing.Button buttonS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelPic;
    private Login.PanelCustom panelCustom1;
    // End of variables declaration//GEN-END:variables
}
